// Code generated by protoc-gen-go. DO NOT EDIT.
// source: punch.proto

package punch_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Punch struct {
	Version              *string  `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Addresses            []string `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
	NatStatus            *int32   `protobuf:"varint,3,opt,name=natStatus" json:"natStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Punch) Reset()         { *m = Punch{} }
func (m *Punch) String() string { return proto.CompactTextString(m) }
func (*Punch) ProtoMessage()    {}
func (*Punch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bab6304f55a920e, []int{0}
}

func (m *Punch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Punch.Unmarshal(m, b)
}
func (m *Punch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Punch.Marshal(b, m, deterministic)
}
func (m *Punch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Punch.Merge(m, src)
}
func (m *Punch) XXX_Size() int {
	return xxx_messageInfo_Punch.Size(m)
}
func (m *Punch) XXX_DiscardUnknown() {
	xxx_messageInfo_Punch.DiscardUnknown(m)
}

var xxx_messageInfo_Punch proto.InternalMessageInfo

func (m *Punch) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Punch) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Punch) GetNatStatus() int32 {
	if m != nil && m.NatStatus != nil {
		return *m.NatStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*Punch)(nil), "punch.pb.Punch")
}

func init() { proto.RegisterFile("punch.proto", fileDescriptor_5bab6304f55a920e) }

var fileDescriptor_5bab6304f55a920e = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xcd, 0x4b,
	0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x72, 0x92, 0x94, 0x62, 0xb9, 0x58,
	0x03, 0x40, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x86, 0x8b, 0x33, 0x31, 0x25, 0xa5, 0x28, 0xb5,
	0xb8, 0x38, 0xb5, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x33, 0x08, 0x21, 0x00, 0x92, 0xcd, 0x4b,
	0x2c, 0x09, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x42, 0x08,
	0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xbb, 0x8d, 0x26, 0x76, 0x00, 0x00, 0x00,
}
